# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FotoDB.ui',
# licensing of 'FotoDB.ui' applies.
#
# Created: Thu Sep  5 23:37:04 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 753)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImLoad_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImLoad_button.sizePolicy().hasHeightForWidth())
        self.ImLoad_button.setSizePolicy(sizePolicy)
        self.ImLoad_button.setObjectName("ImLoad_button")
        self.horizontalLayout.addWidget(self.ImLoad_button)
        self.ImClear_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImClear_button.sizePolicy().hasHeightForWidth())
        self.ImClear_button.setSizePolicy(sizePolicy)
        self.ImClear_button.setObjectName("ImClear_button")
        self.horizontalLayout.addWidget(self.ImClear_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(421, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.EventLable = QtWidgets.QLabel(self.centralwidget)
        self.EventLable.setObjectName("EventLable")
        self.verticalLayout_4.addWidget(self.EventLable)
        self.event_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_comboBox.sizePolicy().hasHeightForWidth())
        self.event_comboBox.setSizePolicy(sizePolicy)
        self.event_comboBox.setMinimumSize(QtCore.QSize(143, 0))
        self.event_comboBox.setEditable(True)
        self.event_comboBox.setObjectName("event_comboBox")
        self.verticalLayout_4.addWidget(self.event_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.loc_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.loc_comboBox.setEditable(True)
        self.loc_comboBox.setObjectName("loc_comboBox")
        self.verticalLayout_6.addWidget(self.loc_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.etype_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.etype_comboBox.setEditable(True)
        self.etype_comboBox.setObjectName("etype_comboBox")
        self.verticalLayout_5.addWidget(self.etype_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.YearLable = QtWidgets.QLabel(self.centralwidget)
        self.YearLable.setMinimumSize(QtCore.QSize(143, 0))
        self.YearLable.setObjectName("YearLable")
        self.horizontalLayout_4.addWidget(self.YearLable)
        self.year_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_comboBox.sizePolicy().hasHeightForWidth())
        self.year_comboBox.setSizePolicy(sizePolicy)
        self.year_comboBox.setMinimumSize(QtCore.QSize(60, 0))
        self.year_comboBox.setEditable(True)
        self.year_comboBox.setObjectName("year_comboBox")
        self.horizontalLayout_4.addWidget(self.year_comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(172, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(421, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.NameOrder_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameOrder_label.sizePolicy().hasHeightForWidth())
        self.NameOrder_label.setSizePolicy(sizePolicy)
        self.NameOrder_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NameOrder_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.NameOrder_label.setObjectName("NameOrder_label")
        self.horizontalLayout_3.addWidget(self.NameOrder_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AuthorLable = QtWidgets.QLabel(self.centralwidget)
        self.AuthorLable.setObjectName("AuthorLable")
        self.horizontalLayout_2.addWidget(self.AuthorLable)
        self.Author_cb = QtWidgets.QComboBox(self.centralwidget)
        self.Author_cb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Author_cb.sizePolicy().hasHeightForWidth())
        self.Author_cb.setSizePolicy(sizePolicy)
        self.Author_cb.setMinimumSize(QtCore.QSize(250, 0))
        self.Author_cb.setEditable(True)
        self.Author_cb.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Author_cb.setObjectName("Author_cb")
        self.horizontalLayout_2.addWidget(self.Author_cb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PeopleLablel = QtWidgets.QLabel(self.centralwidget)
        self.PeopleLablel.setObjectName("PeopleLablel")
        self.horizontalLayout_6.addWidget(self.PeopleLablel)
        self.People_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.People_comboBox.sizePolicy().hasHeightForWidth())
        self.People_comboBox.setSizePolicy(sizePolicy)
        self.People_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.People_comboBox.setEditable(True)
        self.People_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.People_comboBox.setObjectName("People_comboBox")
        self.horizontalLayout_6.addWidget(self.People_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RemovePeople_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemovePeople_button.sizePolicy().hasHeightForWidth())
        self.RemovePeople_button.setSizePolicy(sizePolicy)
        self.RemovePeople_button.setObjectName("RemovePeople_button")
        self.verticalLayout.addWidget(self.RemovePeople_button)
        self.ClearPeopleList_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearPeopleList_button.sizePolicy().hasHeightForWidth())
        self.ClearPeopleList_button.setSizePolicy(sizePolicy)
        self.ClearPeopleList_button.setObjectName("ClearPeopleList_button")
        self.verticalLayout.addWidget(self.ClearPeopleList_button)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.people_listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.people_listWidget.sizePolicy().hasHeightForWidth())
        self.people_listWidget.setSizePolicy(sizePolicy)
        self.people_listWidget.setMaximumSize(QtCore.QSize(250, 65))
        self.people_listWidget.setAcceptDrops(False)
        self.people_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.people_listWidget.setObjectName("people_listWidget")
        self.horizontalLayout_7.addWidget(self.people_listWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(421, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.CommentLable = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CommentLable.sizePolicy().hasHeightForWidth())
        self.CommentLable.setSizePolicy(sizePolicy)
        self.CommentLable.setObjectName("CommentLable")
        self.horizontalLayout_8.addWidget(self.CommentLable)
        self.Comment_cb = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Comment_cb.sizePolicy().hasHeightForWidth())
        self.Comment_cb.setSizePolicy(sizePolicy)
        self.Comment_cb.setMinimumSize(QtCore.QSize(325, 0))
        self.Comment_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Comment_cb.setEditable(True)
        self.Comment_cb.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Comment_cb.setObjectName("Comment_cb")
        self.horizontalLayout_8.addWidget(self.Comment_cb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(421, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SearchDB_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchDB_button.sizePolicy().hasHeightForWidth())
        self.SearchDB_button.setSizePolicy(sizePolicy)
        self.SearchDB_button.setObjectName("SearchDB_button")
        self.horizontalLayout_9.addWidget(self.SearchDB_button)
        self.AllInsert_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AllInsert_button.sizePolicy().hasHeightForWidth())
        self.AllInsert_button.setSizePolicy(sizePolicy)
        self.AllInsert_button.setObjectName("AllInsert_button")
        self.horizontalLayout_9.addWidget(self.AllInsert_button)
        self.ExportAll_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExportAll_button.sizePolicy().hasHeightForWidth())
        self.ExportAll_button.setSizePolicy(sizePolicy)
        self.ExportAll_button.setObjectName("ExportAll_button")
        self.horizontalLayout_9.addWidget(self.ExportAll_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem10)
        self.SingleImactionLabel = QtWidgets.QLabel(self.centralwidget)
        self.SingleImactionLabel.setWordWrap(True)
        self.SingleImactionLabel.setObjectName("SingleImactionLabel")
        self.verticalLayout_3.addWidget(self.SingleImactionLabel)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.insertRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.insertRadioButton.setChecked(True)
        self.insertRadioButton.setObjectName("insertRadioButton")
        self.horizontalLayout_10.addWidget(self.insertRadioButton)
        self.exportIm_radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.exportIm_radioButton.setObjectName("exportIm_radioButton")
        self.horizontalLayout_10.addWidget(self.exportIm_radioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem11 = QtWidgets.QSpacerItem(421, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(421, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.dbSync_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbSync_pushButton.sizePolicy().hasHeightForWidth())
        self.dbSync_pushButton.setSizePolicy(sizePolicy)
        self.dbSync_pushButton.setObjectName("dbSync_pushButton")
        self.horizontalLayout_11.addWidget(self.dbSync_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem13 = QtWidgets.QSpacerItem(421, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem13)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.ImDisplay = QtWidgets.QVBoxLayout()
        self.ImDisplay.setObjectName("ImDisplay")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.ImDisplay.addItem(spacerItem14)
        self.horizontalLayout_12.addLayout(self.ImDisplay)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.loc_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ImLoad_button, self.ImClear_button)
        MainWindow.setTabOrder(self.ImClear_button, self.year_comboBox)
        MainWindow.setTabOrder(self.year_comboBox, self.Author_cb)
        MainWindow.setTabOrder(self.Author_cb, self.People_comboBox)
        MainWindow.setTabOrder(self.People_comboBox, self.people_listWidget)
        MainWindow.setTabOrder(self.people_listWidget, self.RemovePeople_button)
        MainWindow.setTabOrder(self.RemovePeople_button, self.ClearPeopleList_button)
        MainWindow.setTabOrder(self.ClearPeopleList_button, self.SearchDB_button)
        MainWindow.setTabOrder(self.SearchDB_button, self.AllInsert_button)
        MainWindow.setTabOrder(self.AllInsert_button, self.ExportAll_button)
        MainWindow.setTabOrder(self.ExportAll_button, self.insertRadioButton)
        MainWindow.setTabOrder(self.insertRadioButton, self.exportIm_radioButton)
        MainWindow.setTabOrder(self.exportIm_radioButton, self.dbSync_pushButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Antony", None, -1))
        self.ImLoad_button.setText(QtWidgets.QApplication.translate("MainWindow", "Load image(s)", None, -1))
        self.ImClear_button.setText(QtWidgets.QApplication.translate("MainWindow", "Clear display", None, -1))
        self.EventLable.setText(QtWidgets.QApplication.translate("MainWindow", "Event name:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Location:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Event Type:", None, -1))
        self.YearLable.setText(QtWidgets.QApplication.translate("MainWindow", "Year:", None, -1))
        self.NameOrder_label.setText(QtWidgets.QApplication.translate("MainWindow", "Nick; First; Family name                 ", None, -1))
        self.AuthorLable.setText(QtWidgets.QApplication.translate("MainWindow", "Photographer:", None, -1))
        self.PeopleLablel.setText(QtWidgets.QApplication.translate("MainWindow", "People:", None, -1))
        self.RemovePeople_button.setText(QtWidgets.QApplication.translate("MainWindow", "Remove", None, -1))
        self.ClearPeopleList_button.setText(QtWidgets.QApplication.translate("MainWindow", "Remove all", None, -1))
        self.CommentLable.setText(QtWidgets.QApplication.translate("MainWindow", "Comment:", None, -1))
        self.Comment_cb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "separate more comments by ;", None, -1))
        self.SearchDB_button.setText(QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.AllInsert_button.setText(QtWidgets.QApplication.translate("MainWindow", "Record for all", None, -1))
        self.ExportAll_button.setText(QtWidgets.QApplication.translate("MainWindow", "Export all", None, -1))
        self.SingleImactionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Clicking on single images results in:", None, -1))
        self.insertRadioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Record to db", None, -1))
        self.exportIm_radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Export", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Database operations:", None, -1))
        self.dbSync_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Synchronize 2 databases", None, -1))

