# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FotoDB.ui'
#
# Created: Tue Nov 15 14:57:09 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Antony", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ImLoad_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImLoad_button.sizePolicy().hasHeightForWidth())
        self.ImLoad_button.setSizePolicy(sizePolicy)
        self.ImLoad_button.setText(QtGui.QApplication.translate("MainWindow", "Load image(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.ImLoad_button.setObjectName(_fromUtf8("ImLoad_button"))
        self.horizontalLayout.addWidget(self.ImLoad_button)
        self.ImClear_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImClear_button.sizePolicy().hasHeightForWidth())
        self.ImClear_button.setSizePolicy(sizePolicy)
        self.ImClear_button.setText(QtGui.QApplication.translate("MainWindow", "Clear display", None, QtGui.QApplication.UnicodeUTF8))
        self.ImClear_button.setObjectName(_fromUtf8("ImClear_button"))
        self.horizontalLayout.addWidget(self.ImClear_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.EventLable = QtGui.QLabel(self.centralwidget)
        self.EventLable.setText(QtGui.QApplication.translate("MainWindow", "Event name:", None, QtGui.QApplication.UnicodeUTF8))
        self.EventLable.setObjectName(_fromUtf8("EventLable"))
        self.verticalLayout_4.addWidget(self.EventLable)
        self.event_comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_comboBox.sizePolicy().hasHeightForWidth())
        self.event_comboBox.setSizePolicy(sizePolicy)
        self.event_comboBox.setMinimumSize(QtCore.QSize(143, 0))
        self.event_comboBox.setEditable(True)
        self.event_comboBox.setObjectName(_fromUtf8("event_comboBox"))
        self.verticalLayout_4.addWidget(self.event_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.loc_comboBox = QtGui.QComboBox(self.centralwidget)
        self.loc_comboBox.setEditable(True)
        self.loc_comboBox.setObjectName(_fromUtf8("loc_comboBox"))
        self.verticalLayout_6.addWidget(self.loc_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Event Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.etype_comboBox = QtGui.QComboBox(self.centralwidget)
        self.etype_comboBox.setEditable(True)
        self.etype_comboBox.setObjectName(_fromUtf8("etype_comboBox"))
        self.verticalLayout_5.addWidget(self.etype_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.YearLable = QtGui.QLabel(self.centralwidget)
        self.YearLable.setMinimumSize(QtCore.QSize(132, 0))
        self.YearLable.setText(QtGui.QApplication.translate("MainWindow", "Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.YearLable.setObjectName(_fromUtf8("YearLable"))
        self.horizontalLayout_4.addWidget(self.YearLable)
        self.year_comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_comboBox.sizePolicy().hasHeightForWidth())
        self.year_comboBox.setSizePolicy(sizePolicy)
        self.year_comboBox.setMinimumSize(QtCore.QSize(60, 0))
        self.year_comboBox.setEditable(True)
        self.year_comboBox.setObjectName(_fromUtf8("year_comboBox"))
        self.horizontalLayout_4.addWidget(self.year_comboBox)
        spacerItem2 = QtGui.QSpacerItem(172, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.NameOrder_label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameOrder_label.sizePolicy().hasHeightForWidth())
        self.NameOrder_label.setSizePolicy(sizePolicy)
        self.NameOrder_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NameOrder_label.setText(QtGui.QApplication.translate("MainWindow", "Nick; First; Family name                 ", None, QtGui.QApplication.UnicodeUTF8))
        self.NameOrder_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.NameOrder_label.setObjectName(_fromUtf8("NameOrder_label"))
        self.horizontalLayout_3.addWidget(self.NameOrder_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.AuthorLable = QtGui.QLabel(self.centralwidget)
        self.AuthorLable.setText(QtGui.QApplication.translate("MainWindow", "Photographer:", None, QtGui.QApplication.UnicodeUTF8))
        self.AuthorLable.setObjectName(_fromUtf8("AuthorLable"))
        self.horizontalLayout_2.addWidget(self.AuthorLable)
        self.Author_cb = QtGui.QComboBox(self.centralwidget)
        self.Author_cb.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Author_cb.sizePolicy().hasHeightForWidth())
        self.Author_cb.setSizePolicy(sizePolicy)
        self.Author_cb.setMinimumSize(QtCore.QSize(250, 0))
        self.Author_cb.setEditable(True)
        self.Author_cb.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.Author_cb.setObjectName(_fromUtf8("Author_cb"))
        self.horizontalLayout_2.addWidget(self.Author_cb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.PeopleLablel = QtGui.QLabel(self.centralwidget)
        self.PeopleLablel.setText(QtGui.QApplication.translate("MainWindow", "People:", None, QtGui.QApplication.UnicodeUTF8))
        self.PeopleLablel.setObjectName(_fromUtf8("PeopleLablel"))
        self.horizontalLayout_6.addWidget(self.PeopleLablel)
        self.People_comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.People_comboBox.sizePolicy().hasHeightForWidth())
        self.People_comboBox.setSizePolicy(sizePolicy)
        self.People_comboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.People_comboBox.setEditable(True)
        self.People_comboBox.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.People_comboBox.setObjectName(_fromUtf8("People_comboBox"))
        self.horizontalLayout_6.addWidget(self.People_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.RemovePeople_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemovePeople_button.sizePolicy().hasHeightForWidth())
        self.RemovePeople_button.setSizePolicy(sizePolicy)
        self.RemovePeople_button.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.RemovePeople_button.setObjectName(_fromUtf8("RemovePeople_button"))
        self.verticalLayout.addWidget(self.RemovePeople_button)
        self.ClearPeopleList_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearPeopleList_button.sizePolicy().hasHeightForWidth())
        self.ClearPeopleList_button.setSizePolicy(sizePolicy)
        self.ClearPeopleList_button.setText(QtGui.QApplication.translate("MainWindow", "Remove all", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearPeopleList_button.setObjectName(_fromUtf8("ClearPeopleList_button"))
        self.verticalLayout.addWidget(self.ClearPeopleList_button)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.people_listWidget = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.people_listWidget.sizePolicy().hasHeightForWidth())
        self.people_listWidget.setSizePolicy(sizePolicy)
        self.people_listWidget.setMaximumSize(QtCore.QSize(250, 65))
        self.people_listWidget.setAcceptDrops(False)
        self.people_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.people_listWidget.setObjectName(_fromUtf8("people_listWidget"))
        self.horizontalLayout_7.addWidget(self.people_listWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.CommentLable = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CommentLable.sizePolicy().hasHeightForWidth())
        self.CommentLable.setSizePolicy(sizePolicy)
        self.CommentLable.setText(QtGui.QApplication.translate("MainWindow", "Comment:", None, QtGui.QApplication.UnicodeUTF8))
        self.CommentLable.setObjectName(_fromUtf8("CommentLable"))
        self.horizontalLayout_8.addWidget(self.CommentLable)
        self.CommentInput_text = QtGui.QPlainTextEdit(self.centralwidget)
        self.CommentInput_text.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CommentInput_text.sizePolicy().hasHeightForWidth())
        self.CommentInput_text.setSizePolicy(sizePolicy)
        self.CommentInput_text.setMaximumSize(QtCore.QSize(0, 0))
        self.CommentInput_text.setTabChangesFocus(True)
        self.CommentInput_text.setObjectName(_fromUtf8("CommentInput_text"))
        self.horizontalLayout_8.addWidget(self.CommentInput_text)
        self.Comment_cb = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Comment_cb.sizePolicy().hasHeightForWidth())
        self.Comment_cb.setSizePolicy(sizePolicy)
        self.Comment_cb.setMinimumSize(QtCore.QSize(325, 0))
        self.Comment_cb.setToolTip(QtGui.QApplication.translate("MainWindow", "separate more comments by ;", None, QtGui.QApplication.UnicodeUTF8))
        self.Comment_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Comment_cb.setEditable(True)
        self.Comment_cb.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.Comment_cb.setObjectName(_fromUtf8("Comment_cb"))
        self.horizontalLayout_8.addWidget(self.Comment_cb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem7 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.SearchDB_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchDB_button.sizePolicy().hasHeightForWidth())
        self.SearchDB_button.setSizePolicy(sizePolicy)
        self.SearchDB_button.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchDB_button.setObjectName(_fromUtf8("SearchDB_button"))
        self.horizontalLayout_9.addWidget(self.SearchDB_button)
        self.AllInsert_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AllInsert_button.sizePolicy().hasHeightForWidth())
        self.AllInsert_button.setSizePolicy(sizePolicy)
        self.AllInsert_button.setText(QtGui.QApplication.translate("MainWindow", "Record for all", None, QtGui.QApplication.UnicodeUTF8))
        self.AllInsert_button.setObjectName(_fromUtf8("AllInsert_button"))
        self.horizontalLayout_9.addWidget(self.AllInsert_button)
        self.ExportAll_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExportAll_button.sizePolicy().hasHeightForWidth())
        self.ExportAll_button.setSizePolicy(sizePolicy)
        self.ExportAll_button.setText(QtGui.QApplication.translate("MainWindow", "Export all", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportAll_button.setObjectName(_fromUtf8("ExportAll_button"))
        self.horizontalLayout_9.addWidget(self.ExportAll_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem9)
        self.SingleImactionLabel = QtGui.QLabel(self.centralwidget)
        self.SingleImactionLabel.setText(QtGui.QApplication.translate("MainWindow", "Clicking on single images results in:", None, QtGui.QApplication.UnicodeUTF8))
        self.SingleImactionLabel.setWordWrap(True)
        self.SingleImactionLabel.setObjectName(_fromUtf8("SingleImactionLabel"))
        self.verticalLayout_3.addWidget(self.SingleImactionLabel)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.insertRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.insertRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Record to db", None, QtGui.QApplication.UnicodeUTF8))
        self.insertRadioButton.setChecked(True)
        self.insertRadioButton.setObjectName(_fromUtf8("insertRadioButton"))
        self.horizontalLayout_10.addWidget(self.insertRadioButton)
        self.exportIm_radioButton = QtGui.QRadioButton(self.centralwidget)
        self.exportIm_radioButton.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.exportIm_radioButton.setObjectName(_fromUtf8("exportIm_radioButton"))
        self.horizontalLayout_10.addWidget(self.exportIm_radioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem10 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Database operations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_11.addWidget(self.label)
        self.dbSync_pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbSync_pushButton.sizePolicy().hasHeightForWidth())
        self.dbSync_pushButton.setSizePolicy(sizePolicy)
        self.dbSync_pushButton.setText(QtGui.QApplication.translate("MainWindow", "Synchronize 2 databases", None, QtGui.QApplication.UnicodeUTF8))
        self.dbSync_pushButton.setObjectName(_fromUtf8("dbSync_pushButton"))
        self.horizontalLayout_11.addWidget(self.dbSync_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem12 = QtGui.QSpacerItem(421, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.ImDisplay = QtGui.QVBoxLayout()
        self.ImDisplay.setObjectName(_fromUtf8("ImDisplay"))
        self.horizontalLayout_12.addLayout(self.ImDisplay)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.loc_comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ImLoad_button, self.ImClear_button)
        MainWindow.setTabOrder(self.ImClear_button, self.year_comboBox)
        MainWindow.setTabOrder(self.year_comboBox, self.Author_cb)
        MainWindow.setTabOrder(self.Author_cb, self.People_comboBox)
        MainWindow.setTabOrder(self.People_comboBox, self.people_listWidget)
        MainWindow.setTabOrder(self.people_listWidget, self.RemovePeople_button)
        MainWindow.setTabOrder(self.RemovePeople_button, self.ClearPeopleList_button)
        MainWindow.setTabOrder(self.ClearPeopleList_button, self.CommentInput_text)
        MainWindow.setTabOrder(self.CommentInput_text, self.SearchDB_button)
        MainWindow.setTabOrder(self.SearchDB_button, self.AllInsert_button)
        MainWindow.setTabOrder(self.AllInsert_button, self.ExportAll_button)
        MainWindow.setTabOrder(self.ExportAll_button, self.insertRadioButton)
        MainWindow.setTabOrder(self.insertRadioButton, self.exportIm_radioButton)
        MainWindow.setTabOrder(self.exportIm_radioButton, self.dbSync_pushButton)

    def retranslateUi(self, MainWindow):
        pass

